name: Build app and Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd core && npm install && cd ..
    - run: cd client && npm install && cd ..
    - run: npm --prefix=client run build_prod
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tanacsg/blockchain-poll:0.33.$GITHUB_RUN_NUMBER --tag tanacsg/blockchain-poll:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: tanacsg
          password: ${{ secrets.TANACSG_TOKEN }}
    - name: Build the Docker image
      run: docker push tanacsg/blockchain-poll --all-tags
